-- Phase 12 changes what a row means twice over: a lexeme is not a lemma, and a
-- translation belongs to a form rather than to a meaning. Nothing in the old rows
-- records which part of speech a stored form realises, or how that form should be
-- rendered, so they cannot be migrated. Clearing first lets the statements below
-- state the target shape rather than negotiate with the old one, as 0003 did.
-- CASCADE reaches dict_variants, dict_senses, dict_var_translations, questions,
-- session_questions and answers. sessions is named because nothing references it.
-- users is untouched.
TRUNCATE dict_lexemes, sessions CASCADE;--> statement-breakpoint

-- Generated by drizzle-kit, with one edit: it emitted the new PRIMARY KEY above
-- the ADD COLUMN for the variant_id that key is on, which cannot run. The
-- columns are added first here, and nothing else was changed.
ALTER TABLE "dict_senses" DROP CONSTRAINT "dict_senses_lexeme_rank_key";--> statement-breakpoint
ALTER TABLE "dict_lexemes" DROP CONSTRAINT "dict_lexemes_language_lemma_key";--> statement-breakpoint
ALTER TABLE "dict_senses" DROP CONSTRAINT "dict_senses_rank_nonneg";--> statement-breakpoint
ALTER TABLE "dict_var_translations" DROP CONSTRAINT "dict_var_translations_sense_id_user_language_code_pk";--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD COLUMN "variant_id" text NOT NULL;--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD COLUMN "example_source" text;--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD COLUMN "rank" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "dict_lexemes" ADD COLUMN "part_of_speech" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD CONSTRAINT "dict_var_translations_variant_id_sense_id_user_language_code_pk" PRIMARY KEY("variant_id","sense_id","user_language_code");--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD CONSTRAINT "dict_var_translations_variant_id_dict_variants_id_fk" FOREIGN KEY ("variant_id") REFERENCES "public"."dict_variants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dict_senses" DROP COLUMN "part_of_speech";--> statement-breakpoint
ALTER TABLE "dict_senses" DROP COLUMN "rank";--> statement-breakpoint
ALTER TABLE "dict_senses" DROP COLUMN "example_source";--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD CONSTRAINT "dict_var_translations_variant_rank_key" UNIQUE("variant_id","user_language_code","rank");--> statement-breakpoint
ALTER TABLE "dict_senses" ADD CONSTRAINT "dict_senses_lexeme_code_key" UNIQUE("lexeme_id","sense_code");--> statement-breakpoint
ALTER TABLE "dict_lexemes" ADD CONSTRAINT "dict_lexemes_language_lemma_pos_key" UNIQUE("language_code","lemma","part_of_speech");--> statement-breakpoint
ALTER TABLE "dict_var_translations" ADD CONSTRAINT "dict_var_translations_rank_nonneg" CHECK ("dict_var_translations"."rank" >= 0);
