// Recorded provider answers, one per seeded string. Generated by
// `npm run content:generate` and reviewed by hand; db/seed.ts replays these
// through persistEntries, the same write path a lookup uses, which is why a
// seeded row and a looked-up row are indistinguishable.
//
// DO NOT EDIT BY HAND. Re-record one string with
// `npm run content:generate -- <query>`, read the diff, and commit it.
import type { LlmTranslation } from '@lang-tutor/core/api';

export const recorded: Record<string, LlmTranslation> = {
  "window": {
    "kind": "word",
    "entries": [
      {
        "lemma": "window",
        "senses": [
          {
            "translation": "חלון",
            "part_of_speech": "noun",
            "example": {
              "source": "Please close the window.",
              "target": "בבקשה תסגור את החלון."
            },
            "sense_code": "building_opening"
          },
          {
            "translation": "חלון",
            "part_of_speech": "noun",
            "example": {
              "source": "Close the browser window.",
              "target": "סגור את חלון הדפדפן."
            },
            "sense_code": "computer_interface"
          },
          {
            "translation": "חלון הזדמנויות",
            "part_of_speech": "noun",
            "example": {
              "source": "There's a small window of opportunity to apply for the job.",
              "target": "יש חלון הזדמנויות קטן להגיש מועמדות לעבודה."
            },
            "sense_code": "period_of_opportunity"
          }
        ]
      }
    ]
  },
  "book": {
    "kind": "word",
    "entries": [
      {
        "lemma": "book",
        "senses": [
          {
            "translation": "ספר",
            "part_of_speech": "noun",
            "example": {
              "source": "I read a good book.",
              "target": "קראתי ספר טוב."
            },
            "sense_code": "written_work"
          },
          {
            "translation": "להזמין",
            "part_of_speech": "verb",
            "example": {
              "source": "I want to book a table.",
              "target": "אני רוצה להזמין שולחן."
            },
            "sense_code": "make_reservation"
          }
        ]
      }
    ]
  },
  "water": {
    "kind": "word",
    "entries": [
      {
        "lemma": "water",
        "senses": [
          {
            "translation": "מים",
            "part_of_speech": "noun",
            "example": {
              "source": "I need a glass of water.",
              "target": "אני צריך כוס מים."
            },
            "sense_code": "liquid_h2o"
          },
          {
            "translation": "להשקות",
            "part_of_speech": "verb",
            "example": {
              "source": "Don't forget to water the plants.",
              "target": "אל תשכח להשקות את הצמחים."
            },
            "sense_code": "provide_liquid_to_plants"
          }
        ]
      }
    ]
  },
  "friend": {
    "kind": "word",
    "entries": [
      {
        "lemma": "friend",
        "senses": [
          {
            "translation": "חבר",
            "part_of_speech": "noun",
            "example": {
              "source": "My best friend is coming to visit.",
              "target": "החבר הכי טוב שלי בא לבקר."
            },
            "sense_code": "person_one_knows_and_likes"
          }
        ]
      }
    ]
  },
  "difficult": {
    "kind": "word",
    "entries": [
      {
        "lemma": "difficult",
        "senses": [
          {
            "translation": "קשה",
            "part_of_speech": "adjective",
            "example": {
              "source": "It was a difficult decision to make.",
              "target": "זו הייתה החלטה קשה לקבל."
            },
            "sense_code": "hard_to_do"
          }
        ]
      }
    ]
  },
  "to remember": {
    "kind": "word",
    "entries": [
      {
        "lemma": "remember",
        "senses": [
          {
            "translation": "לזכור",
            "part_of_speech": "verb",
            "example": {
              "source": "I need to remember to buy milk.",
              "target": "אני צריך לזכור לקנות חלב."
            },
            "sense_code": "recall_information"
          }
        ]
      }
    ]
  },
  "excuse me": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "excuse me",
        "senses": [
          {
            "translation": "סליחה",
            "part_of_speech": "interjection",
            "example": {
              "source": "Excuse me, could you tell me the way to the station?",
              "target": "סליחה, תוכל לומר לי את הדרך לתחנה?"
            },
            "sense_code": "polite_interjection"
          }
        ]
      }
    ]
  },
  "good morning": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "good morning",
        "senses": [
          {
            "translation": "בוקר טוב",
            "sense_code": "morning_greeting"
          }
        ]
      }
    ]
  },
  "thank you very much": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "thank you very much",
        "senses": [
          {
            "translation": "תודה רבה",
            "sense_code": "expression_of_gratitude"
          }
        ]
      }
    ]
  },
  "How do you do?": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "How do you do?",
        "senses": [
          {
            "translation": "מה שלומך?",
            "part_of_speech": "interjection",
            "example": {
              "source": "Good morning, Mr. Smith. How do you do?",
              "target": "בוקר טוב, אדון סמית'. מה שלומך?"
            },
            "sense_code": "formal_greeting_inquiry_well_being"
          }
        ]
      }
    ]
  },
  "see you later": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "see you later",
        "senses": [
          {
            "translation": "נתראה אחר כך",
            "part_of_speech": "interjection",
            "example": {
              "source": "I have to go now, see you later!",
              "target": "אני חייב ללכת עכשיו, נתראה אחר כך!"
            },
            "sense_code": "farewell_expression"
          }
        ]
      }
    ]
  },
  "Have a nice day!": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Have a nice day!",
        "senses": [
          {
            "translation": "שיהיה לך יום נעים!",
            "part_of_speech": "greeting",
            "example": {
              "source": "I'm leaving now. Have a nice day!",
              "target": "אני הולך עכשיו. שיהיה לך יום נעים!"
            },
            "sense_code": "greeting_wish_for_good_day"
          }
        ]
      }
    ]
  },
  "Nice to meet you": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Nice to meet you",
        "senses": [
          {
            "translation": "נעים מאוד",
            "sense_code": "greeting_upon_introduction"
          }
        ]
      }
    ]
  }
};
