// Authoring source for the shared content the seed inserts. Not runtime data:
// nothing reads this at request time — `repo/questions.ts` reads the database.
// Moved here from src/data/mockQuestions.ts in phase 4.

export type ContentEntry = {
  question_id: string;
  term_id: string;
  lemma: string;
  part_of_speech: string;
  prompt: string;
  prompt_kind: string;
  translation: string;
  options: string[];
  correct_option: number;
};

export const content: ContentEntry[] = [
  {
    question_id: 'q-window',
    term_id: 'vt-en-window',
    lemma: 'window',
    part_of_speech: 'noun',
    prompt: 'window',
    prompt_kind: 'base',
    translation: 'חלון',
    options: ['דלת', 'חלון', 'שולחן', 'קיר'],
    correct_option: 1,
  },
  {
    question_id: 'q-book',
    term_id: 'vt-en-book',
    lemma: 'book',
    part_of_speech: 'noun',
    prompt: 'book',
    prompt_kind: 'base',
    translation: 'ספר',
    options: ['ספר', 'עיפרון', 'מחשב', 'כיסא'],
    correct_option: 0,
  },
  {
    question_id: 'q-water',
    term_id: 'vt-en-water',
    lemma: 'water',
    part_of_speech: 'noun',
    prompt: 'water',
    prompt_kind: 'base',
    translation: 'מים',
    options: ['לחם', 'חלב', 'מים', 'קפה'],
    correct_option: 2,
  },
  {
    question_id: 'q-friend',
    term_id: 'vt-en-friend',
    lemma: 'friend',
    part_of_speech: 'noun',
    prompt: 'friend',
    prompt_kind: 'base',
    translation: 'חבר',
    options: ['שכן', 'מורה', 'רופא', 'חבר'],
    correct_option: 3,
  },
  {
    question_id: 'q-difficult',
    term_id: 'vt-en-difficult',
    lemma: 'difficult',
    part_of_speech: 'adjective',
    prompt: 'difficult',
    prompt_kind: 'base',
    translation: 'קשה',
    options: ['קל', 'קשה', 'חשוב', 'מהיר'],
    correct_option: 1,
  },
  {
    question_id: 'q-remember',
    term_id: 'vt-en-remember',
    lemma: 'remember',
    part_of_speech: 'verb',
    prompt: 'to remember',
    prompt_kind: 'infinitive',
    translation: 'לזכור',
    options: ['לשכוח', 'לזכור', 'ללמוד', 'לחשוב'],
    correct_option: 1,
  },
  {
    question_id: 'q-excuse-me',
    term_id: 'vt-en-excuse-me',
    lemma: 'excuse me',
    part_of_speech: 'phrase',
    prompt: 'excuse me',
    prompt_kind: 'base',
    translation: 'סליחה',
    options: ['שלום', 'תודה', 'סליחה', 'בבקשה'],
    correct_option: 2,
  },
  {
    question_id: 'q-good-morning',
    term_id: 'vt-en-good-morning',
    lemma: 'good morning',
    part_of_speech: 'phrase',
    prompt: 'good morning',
    prompt_kind: 'base',
    translation: 'בוקר טוב',
    options: ['לילה טוב', 'בוקר טוב', 'ערב טוב', 'שבוע טוב'],
    correct_option: 1,
  },
  {
    question_id: 'q-thank-you-very-much',
    term_id: 'vt-en-thank-you-very-much',
    lemma: 'thank you very much',
    part_of_speech: 'phrase',
    prompt: 'thank you very much',
    prompt_kind: 'base',
    translation: 'תודה רבה',
    options: ['תודה רבה', 'בבקשה רבה', 'סליחה רבה', 'שלום רב'],
    correct_option: 0,
  },
  {
    question_id: 'q-how-do-you-do',
    term_id: 'vt-en-how-do-you-do',
    lemma: 'How do you do?',
    part_of_speech: 'phrase',
    prompt: 'How do you do?',
    prompt_kind: 'base',
    translation: 'מה נשמע?',
    options: ['מה השעה?', 'מה נשמע?', 'מה קרה?', 'מה זה?'],
    correct_option: 1,
  },
  {
    question_id: 'q-see-you-later',
    term_id: 'vt-en-see-you-later',
    lemma: 'see you later',
    part_of_speech: 'phrase',
    prompt: 'see you later',
    prompt_kind: 'base',
    translation: 'נתראה אחר כך',
    options: ['נתראה מחר', 'נתראה אחר כך', 'ניפגש בבוקר', 'נדבר בהמשך'],
    correct_option: 1,
  },
  {
    question_id: 'q-i-dont-understand',
    term_id: 'vt-en-i-dont-understand',
    lemma: "I don't understand",
    part_of_speech: 'phrase',
    prompt: "I don't understand",
    prompt_kind: 'base',
    translation: 'אני לא מבין',
    options: ['אני לא יודע', 'אני לא שומע', 'אני לא מבין', 'אני לא זוכר'],
    correct_option: 2,
  },
  {
    question_id: 'q-what-is-your-name',
    term_id: 'vt-en-what-is-your-name',
    lemma: 'What is your name?',
    part_of_speech: 'phrase',
    prompt: 'What is your name?',
    prompt_kind: 'base',
    translation: 'איך קוראים לך?',
    options: ['מאיפה אתה?', 'איך קוראים לך?', 'בן כמה אתה?', 'מה אתה עושה?'],
    correct_option: 1,
  },
  {
    question_id: 'q-have-a-nice-day',
    term_id: 'vt-en-have-a-nice-day',
    lemma: 'Have a nice day!',
    part_of_speech: 'phrase',
    prompt: 'Have a nice day!',
    prompt_kind: 'base',
    translation: 'שיהיה לך יום נעים!',
    options: [
      'שיהיה לך יום נעים!',
      'שיהיה לך בוקר טוב!',
      'שיהיה לך שבוע טוב!',
      'שיהיה לך לילה טוב!',
    ],
    correct_option: 0,
  },
  {
    question_id: 'q-where-is-the-station',
    term_id: 'vt-en-where-is-the-station',
    lemma: 'Where is the station?',
    part_of_speech: 'phrase',
    prompt: 'Where is the station?',
    prompt_kind: 'base',
    translation: 'איפה התחנה?',
    options: ['איפה הבית?', 'איפה השוק?', 'איפה התחנה?', 'איפה הרחוב?'],
    correct_option: 2,
  },
  {
    question_id: 'q-nice-to-meet-you',
    term_id: 'vt-en-nice-to-meet-you',
    lemma: 'Nice to meet you',
    part_of_speech: 'phrase',
    prompt: 'Nice to meet you',
    prompt_kind: 'base',
    translation: 'נעים להכיר',
    options: ['נעים להכיר', 'טוב לראות אותך', 'נתראה בקרוב', 'תודה שבאת'],
    correct_option: 0,
  },
];
