// Recorded provider answers, one per seeded string. Generated by
// `npm run content:generate` and reviewed by hand; db/seed.ts replays these
// through persistEntries, the same write path a lookup uses, which is why a
// seeded row and a looked-up row are indistinguishable.
//
// DO NOT EDIT BY HAND. Re-record one string with
// `npm run content:generate -- <query>`, read the diff, and commit it.
import type { LlmTranslation } from '@lang-tutor/core/api';

export const recorded: Record<string, LlmTranslation> = {
  "window": {
    "kind": "word",
    "entries": [
      {
        "lemma": "window",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "חלון",
            "example": {
              "source": "Please close the window.",
              "target": "בבקשה סגור את החלון."
            },
            "sense_code": "architectural_opening"
          }
        ]
      }
    ]
  },
  "book": {
    "kind": "word",
    "entries": [
      {
        "lemma": "book",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "ספר",
            "example": {
              "source": "I read a good book last night.",
              "target": "קראתי ספר טוב אתמול בלילה."
            },
            "sense_code": "printed_work"
          }
        ]
      },
      {
        "lemma": "book",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "להזמין",
            "example": {
              "source": "I need to book a flight for my trip.",
              "target": "אני צריך להזמין טיסה לנסיעה שלי."
            },
            "sense_code": "make_reservation"
          },
          {
            "translation": "לרשום",
            "example": {
              "source": "The police officer booked him for speeding.",
              "target": "השוטר רשם אותו על נהיגה במהירות מופרזת."
            },
            "sense_code": "record_information"
          }
        ]
      }
    ]
  },
  "water": {
    "kind": "word",
    "entries": [
      {
        "lemma": "water",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "מים",
            "example": {
              "source": "I drank some water.",
              "target": "שתיתי קצת מים."
            },
            "sense_code": "liquid_substance"
          },
          {
            "translation": "מים",
            "example": {
              "source": "The water was cold.",
              "target": "המים היו קרים."
            },
            "sense_code": "body_of_water"
          }
        ]
      },
      {
        "lemma": "water",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "להשקות",
            "example": {
              "source": "I need to water the garden.",
              "target": "אני צריך להשקות את הגינה."
            },
            "sense_code": "provide_liquid_to_plants_animals"
          },
          {
            "translation": "לדמוע",
            "example": {
              "source": "My eyes water when I cut onions.",
              "target": "העיניים שלי דומעות כשאני חותך בצל."
            },
            "sense_code": "eyes_produce_tears"
          }
        ]
      }
    ]
  },
  "friend": {
    "kind": "word",
    "entries": [
      {
        "lemma": "friend",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "חבר",
            "example": {
              "source": "He is my friend.",
              "target": "הוא חבר שלי."
            },
            "sense_code": "male_acquaintance"
          },
          {
            "translation": "חברה",
            "example": {
              "source": "She is my friend.",
              "target": "היא חברה שלי."
            },
            "sense_code": "female_acquaintance"
          }
        ]
      }
    ]
  },
  "difficult": {
    "kind": "word",
    "entries": [
      {
        "lemma": "difficult",
        "part_of_speech": "adjective",
        "senses": [
          {
            "translation": "קשה",
            "example": {
              "source": "The exam was very difficult.",
              "target": "המבחן היה קשה מאוד."
            },
            "sense_code": "hard_to_do"
          },
          {
            "translation": "קשה",
            "example": {
              "source": "He is a difficult child.",
              "target": "הוא ילד קשה."
            },
            "sense_code": "hard_to_please"
          }
        ]
      }
    ]
  },
  "to remember": {
    "kind": "word",
    "entries": [
      {
        "lemma": "remember",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "לזכור",
            "example": {
              "source": "I need to remember to buy milk.",
              "target": "אני צריך לזכור לקנות חלב."
            },
            "sense_code": "recall_from_memory"
          }
        ]
      }
    ]
  },
  "excuse me": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "excuse me",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "סליחה",
            "example": {
              "source": "Excuse me, could you tell me the way to the station?",
              "target": "סליחה, תוכל לומר לי את הדרך לתחנה?"
            },
            "sense_code": "polite_interjection"
          }
        ]
      }
    ]
  },
  "good morning": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "good morning",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "בוקר טוב",
            "example": {
              "source": "She said good morning to everyone in the office.",
              "target": "היא אמרה בוקר טוב לכולם במשרד."
            },
            "sense_code": "morning_greeting"
          }
        ]
      }
    ]
  },
  "thank you very much": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "thank you very much",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "תודה רבה",
            "example": {
              "source": "Thank you very much for your help.",
              "target": "תודה רבה על עזרתך."
            },
            "sense_code": "strong_gratitude"
          }
        ]
      }
    ]
  },
  "How do you do?": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "How do you do?",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "מה שלומך?",
            "sense_code": "greeting"
          }
        ]
      }
    ]
  },
  "see you later": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "see you later",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "נתראה אחר כך",
            "sense_code": "farewell_phrase"
          }
        ]
      }
    ]
  },
  "Have a nice day!": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Have a nice day!",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "שיהיה לך יום נעים!",
            "example": {
              "source": "Goodbye! Have a nice day!",
              "target": "להתראות! שיהיה לך יום נעים!"
            },
            "sense_code": "farewell_greeting"
          }
        ]
      }
    ]
  },
  "Nice to meet you": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Nice to meet you",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "נעים מאוד",
            "example": {
              "source": "Nice to meet you, Sarah.",
              "target": "נעים מאוד, שרה."
            },
            "sense_code": "social_greeting"
          }
        ]
      }
    ]
  }
};
