// Recorded provider answers, one per seeded string. Generated by
// `npm run content:generate` and reviewed by hand; db/seed.ts replays these
// through persistEntries, the same write path a lookup uses, which is why a
// seeded row and a looked-up row are indistinguishable.
//
// DO NOT EDIT BY HAND. Re-record one string with
// `npm run content:generate -- <query>`, read the diff, and commit it.
import type { LlmTranslation } from '@lang-tutor/core/api';

export const recorded: Record<string, LlmTranslation> = {
  "window": {
    "kind": "word",
    "entries": [
      {
        "lemma": "window",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "חלון",
            "example": {
              "source": "She opened the window to let in some fresh air.",
              "target": "היא פתחה את החלון כדי להכניס אוויר צח."
            },
            "sense_code": "architectural_opening"
          },
          {
            "translation": "חלון",
            "example": {
              "source": "The ball hit the window and shattered the glass.",
              "target": "הכדור פגע בחלון וניפץ את הזכוכית."
            },
            "sense_code": "glass_pane"
          },
          {
            "translation": "חלון",
            "example": {
              "source": "We have a narrow window to launch the product before our competitors.",
              "target": "יש לנו חלון צר להשיק את המוצר לפני המתחרים שלנו."
            },
            "sense_code": "time_period_opportunity"
          },
          {
            "translation": "חלון",
            "example": {
              "source": "Click the 'X' icon to close the window.",
              "target": "לחץ על סמל ה-'X' כדי לסגור את החלון."
            },
            "sense_code": "computer_interface_element"
          }
        ]
      }
    ]
  },
  "book": {
    "kind": "word",
    "entries": [
      {
        "lemma": "book",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "ספר",
            "example": {
              "source": "I read a good book yesterday.",
              "target": "קראתי ספר טוב אתמול."
            },
            "sense_code": "written_work"
          }
        ]
      },
      {
        "lemma": "book",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "להזמין",
            "example": {
              "source": "I need to book a flight for next month.",
              "target": "אני צריך להזמין טיסה לחודש הבא."
            },
            "sense_code": "make_reservation"
          },
          {
            "translation": "לרשום",
            "example": {
              "source": "The police officer will book him for speeding.",
              "target": "השוטר ירשום אותו על נהיגה מהירה."
            },
            "sense_code": "record_information"
          }
        ]
      }
    ]
  },
  "water": {
    "kind": "word",
    "entries": [
      {
        "lemma": "water",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "מים",
            "example": {
              "source": "I need a glass of water.",
              "target": "אני צריך כוס מים."
            },
            "sense_code": "liquid_h2o"
          }
        ]
      },
      {
        "lemma": "water",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "להשקות",
            "example": {
              "source": "Please water the plants every morning.",
              "target": "בבקשה תשקה את הצמחים כל בוקר."
            },
            "sense_code": "irrigate_plants"
          },
          {
            "translation": "לדמוע",
            "example": {
              "source": "My eyes started to water from the strong wind.",
              "target": "העיניים שלי התחילו לדמוע מהרוח החזקה."
            },
            "sense_code": "eyes_tear"
          }
        ]
      }
    ]
  },
  "friend": {
    "kind": "word",
    "entries": [
      {
        "lemma": "friend",
        "part_of_speech": "noun",
        "senses": [
          {
            "translation": "חבר",
            "example": {
              "source": "My friend helped me move last weekend.",
              "target": "החבר שלי עזר לי לעבור דירה בסוף השבוע שעבר."
            },
            "sense_code": "close_acquaintance"
          },
          {
            "translation": "ידיד",
            "example": {
              "source": "He is a friend to all animals.",
              "target": "הוא ידיד של כל בעלי החיים."
            },
            "sense_code": "ally_supporter"
          }
        ]
      }
    ]
  },
  "difficult": {
    "kind": "word",
    "entries": [
      {
        "lemma": "difficult",
        "part_of_speech": "adjective",
        "senses": [
          {
            "translation": "קשה",
            "example": {
              "source": "Learning a new language can be very difficult.",
              "target": "ללמוד שפה חדשה יכול להיות קשה מאוד."
            },
            "sense_code": "hard_to_do_or_understand"
          },
          {
            "translation": "קשה",
            "example": {
              "source": "He is a difficult person to work with.",
              "target": "הוא אדם קשה לעבוד איתו."
            },
            "sense_code": "problematic_to_deal_with"
          }
        ]
      }
    ]
  },
  "to remember": {
    "kind": "word",
    "entries": [
      {
        "lemma": "remember",
        "part_of_speech": "verb",
        "senses": [
          {
            "translation": "לזכור",
            "example": {
              "source": "I need to remember to buy milk.",
              "target": "אני צריך לזכור לקנות חלב."
            },
            "sense_code": "recall_information"
          }
        ]
      }
    ]
  },
  "excuse me": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "excuse me",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "סליחה",
            "example": {
              "source": "Excuse me, do you know the way to the station?",
              "target": "סליחה, אתה יודע את הדרך לתחנה?"
            },
            "sense_code": "polite_interruption_or_apology"
          }
        ]
      }
    ]
  },
  "good morning": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "good morning",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "בוקר טוב",
            "sense_code": "greeting"
          }
        ]
      }
    ]
  },
  "thank you very much": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "thank you very much",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "תודה רבה",
            "example": {
              "source": "Thank you very much for your help.",
              "target": "תודה רבה לך על עזרתך."
            },
            "sense_code": "expression_of_gratitude"
          }
        ]
      }
    ]
  },
  "How do you do?": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "How do you do?",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "מה שלומך?",
            "sense_code": "social_greeting"
          }
        ]
      }
    ]
  },
  "see you later": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "see you later",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "להתראות אחר כך",
            "example": {
              "source": "I have to go now, see you later!",
              "target": "אני חייב ללכת עכשיו, להתראות אחר כך!"
            },
            "sense_code": "farewell_greeting"
          }
        ]
      }
    ]
  },
  "Have a nice day!": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Have a nice day!",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "שיהיה לך יום נעים!",
            "sense_code": "wish_good_day"
          }
        ]
      }
    ]
  },
  "Nice to meet you": {
    "kind": "phrase",
    "entries": [
      {
        "lemma": "Nice to meet you",
        "part_of_speech": "interjection",
        "senses": [
          {
            "translation": "נעים מאוד",
            "example": {
              "source": "Hello, I'm Sarah. Nice to meet you.",
              "target": "שלום, אני שרה. נעים מאוד."
            },
            "sense_code": "social_greeting"
          }
        ]
      }
    ]
  }
};
