import { sql } from 'drizzle-orm';
import {
  check,
  foreignKey,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/** One element of `questions.options`. snake_case: it is stored data, not a TS-only shape. */
export type QuestionOption = { position: number; text: string; is_correct: boolean };

export const users = pgTable(
  'users',
  {
    // Server-issued. Once a username is the client-facing handle, a
    // client-chosen id can only collide or impersonate. Generated by the
    // database rather than the application so no randomness enters a layer
    // ADR 0002 R1 would have to police — the same reason sessions.id does it.
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    username: text('username').notNull().unique(),
    displayName: text('display_name').notNull(),
    age: integer('age').notNull(),
    // No default on either language: onboarding always supplies both, so a
    // default could only mask a bug.
    nativeLanguage: varchar('native_language', { length: 10 }).notNull(),
    targetLanguage: varchar('target_language', { length: 10 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Mirrors UsernameSchema in packages/core exactly. Two enforcement points
    // for one rule is deliberate: the schema gives a 400 with a good message,
    // the constraint is what actually holds when something bypasses the route.
    check('users_username_format', sql`${t.username} ~ '^[a-z0-9_]{3,30}$'`),
    check('users_display_name_length', sql`length(${t.displayName}) between 1 and 60`),
    check('users_age_range', sql`${t.age} between 3 and 120`),
    check('users_languages_differ', sql`${t.nativeLanguage} <> ${t.targetLanguage}`),
  ],
);

export const dictLexemes = pgTable(
  'dict_lexemes',
  {
    // Server-issued from phase 10, as users.id has been since 0001: with the
    // dictionary now written at request time, a client-generated id would mean
    // randomness in a layer ADR 0002 R1 would have to police.
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    languageCode: varchar('language_code', { length: 10 }).notNull(),
    lemma: text('lemma').notNull(),
    // A lexeme: the pair of a lemma and a part of speech. It moved up from the
    // sense, where phase 10 put it. Part of speech does describe a meaning, but
    // it also decides which forms a headword has, and only the lexeme can carry
    // that — which is what stops `booked` reaching the noun's senses.
    partOfSpeech: varchar('part_of_speech', { length: 50 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('dict_lexemes_language_lemma_pos_key').on(t.languageCode, t.lemma, t.partOfSpeech),
  ],
);

export const dictVariants = pgTable(
  'dict_variants',
  {
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    lexemeId: text('lexeme_id')
      .notNull()
      .references(() => dictLexemes.id, { onDelete: 'cascade' }),
    // Copied from the term so the unique index below can exist: the scope that
    // matters is one form in one language, but language lives on dict_lexemes
    // and an index reads one table. A term's language never changes, so the
    // copy cannot go stale — and it earns its keep in the read, which no
    // longer joins dict_lexemes at all.
    languageCode: varchar('language_code', { length: 10 }).notNull(),
    // Stored as it was written; matching is always lower(form). One rule for a
    // recorded `How do you do?` and for a learner who typed `BOOK`.
    form: text('form').notNull(),
    kind: text('kind').notNull(),
    // Which reading of this form this term is, as the model ranked them. It
    // sits on the variant rather than the term because it is a property of the
    // pairing: `saw` ranks `see` first, while `saws` returns `saw` alone at 0.
    entryRank: integer('entry_rank').notNull(),
  },
  (t) => [
    // Per term, so one form may belong to several terms — `saw` is a variant of
    // `see` *and* of `saw`, which is what every lexical source does.
    unique('dict_variants_lexeme_form_key').on(t.lexemeId, t.form),
    check('dict_variants_entry_rank_nonneg', sql`${t.entryRank} >= 0`),
    // Two jobs in one index. Its (language_code, lower(form)) prefix is exactly
    // the read's predicate, so there is no separate lookup index; its third
    // column enforces that no two terms claim the same reading of one form.
    // That cannot currently happen — a written form thereafter hits, and ranks
    // within one write are distinct by construction — which is the point: a
    // safety net for a write bug, exactly like UNIQUE(lexeme_id, rank).
    uniqueIndex('dict_variants_form_entry_rank_key').on(
      t.languageCode,
      sql`lower(${t.form})`,
      t.entryRank,
    ),
  ],
);

export const dictSenses = pgTable(
  'dict_senses',
  {
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    lexemeId: text('lexeme_id')
      .notNull()
      .references(() => dictLexemes.id, { onDelete: 'cascade' }),
    // Model-supplied. Phase 10 called this decoration; from phase 12 it is
    // load-bearing, and the unique key below is why: it is the only handle a
    // later form's translations have on senses this lexeme already holds.
    senseCode: text('sense_code').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  // The table is pure identity now. `part_of_speech` went up to the lexeme, and
  // `rank` and `example_source` went down to the translation: a sense has no
  // order and no example of its own, only a position and a wording within some
  // given form's answer.
  (t) => [unique('dict_senses_lexeme_code_key').on(t.lexemeId, t.senseCode)],
);

export const dictVarTranslations = pgTable(
  'dict_var_translations',
  {
    // The variant joins the key in phase 12, which is what makes an answer
    // belong to the form that was typed: `booked` renders הזמין where `book`
    // renders להזמין, and both are the same sense of the same lexeme.
    variantId: text('variant_id')
      .notNull()
      .references(() => dictVariants.id, { onDelete: 'cascade' }),
    senseId: text('sense_id')
      .notNull()
      .references(() => dictSenses.id, { onDelete: 'cascade' }),
    userLanguageCode: varchar('user_language_code', { length: 10 }).notNull(),
    translation: text('translation').notNull(),
    definitionNotes: text('definition_notes'),
    // Both halves of the example live here, because an example belongs to the
    // form that was typed: `booked` shows "I booked a table", not "I want to
    // book a table". The source half is duplicated per target language, which is
    // cheaper than a fifth table to normalise it.
    exampleSource: text('example_source'),
    exampleTarget: text('example_target'),
    // "Most common first", scoped to THIS form. It sits here rather than on the
    // sense so that a sense a later form introduces lands where that form ranked
    // it, instead of at max(rank)+1 — arrival order wearing a rank's clothes —
    // and so that the lexeme's order does not depend on which form was looked up
    // first. Values are the sense's position in the entry the model returned.
    rank: integer('rank').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.variantId, t.senseId, t.userLanguageCode] }),
    unique('dict_var_translations_variant_rank_key').on(
      t.variantId,
      t.userLanguageCode,
      t.rank,
    ),
    check('dict_var_translations_rank_nonneg', sql`${t.rank} >= 0`),
  ],
);

export const questions = pgTable(
  'questions',
  {
    id: text('id').primaryKey(),
    // Nullable: NULL means shared. Phase 4 writes only shared rows; a later
    // phase writes per-learner ones without a migration.
    userId: text('user_id').references(() => users.id),
    senseId: text('sense_id')
      .notNull()
      .references(() => dictSenses.id),
    promptVariantId: text('prompt_variant_id')
      .notNull()
      .references(() => dictVariants.id),
    targetLanguage: varchar('target_language', { length: 10 }).notNull(),
    userLanguageCode: varchar('user_language_code', { length: 10 }).notNull(),
    type: varchar('type', { length: 50 }).notNull(),
    options: jsonb('options').$type<QuestionOption[]>().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [check('questions_options_valid', sql`question_options_valid(${t.options})`)],
);

export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  // NULL = in progress. There is no separate `complete` column.
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

export const sessionQuestions = pgTable(
  'session_questions',
  {
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id, { onDelete: 'cascade' }),
    position: integer('position').notNull(),
    questionId: text('question_id')
      .notNull()
      .references(() => questions.id),
    // The per-session shuffle: option_order[i] is the canonical position of the
    // option shown at display index i.
    optionOrder: integer('option_order').array().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.sessionId, t.position] }),
    // Exists purely as the composite FK target for `answers`.
    unique('session_questions_position_question_key').on(t.sessionId, t.position, t.questionId),
  ],
);

export const answers = pgTable(
  'answers',
  {
    sessionId: uuid('session_id').notNull(),
    position: integer('position').notNull(),
    questionId: text('question_id').notNull(),
    selectedOptionPosition: integer('selected_option_position').notNull(),
    answeredAt: timestamp('answered_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.sessionId, t.position] }),
    // Makes it impossible to record an answer to a question that was not in
    // this session at this position.
    foreignKey({
      columns: [t.sessionId, t.position, t.questionId],
      foreignColumns: [
        sessionQuestions.sessionId,
        sessionQuestions.position,
        sessionQuestions.questionId,
      ],
    }).onDelete('cascade'),
    check('answers_selected_option_position_nonneg', sql`${t.selectedOptionPosition} >= 0`),
  ],
);
