import { sql } from 'drizzle-orm';
import {
  check,
  foreignKey,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

/** One element of `questions.options`. snake_case: it is stored data, not a TS-only shape. */
export type QuestionOption = { position: number; text: string; is_correct: boolean };

export const users = pgTable(
  'users',
  {
    // Server-issued. Once a username is the client-facing handle, a
    // client-chosen id can only collide or impersonate. Generated by the
    // database rather than the application so no randomness enters a layer
    // ADR 0002 R1 would have to police — the same reason sessions.id does it.
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    username: text('username').notNull().unique(),
    displayName: text('display_name').notNull(),
    age: integer('age').notNull(),
    // No default on either language: onboarding always supplies both, so a
    // default could only mask a bug.
    nativeLanguage: varchar('native_language', { length: 10 }).notNull(),
    targetLanguage: varchar('target_language', { length: 10 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Mirrors UsernameSchema in packages/core exactly. Two enforcement points
    // for one rule is deliberate: the schema gives a 400 with a good message,
    // the constraint is what actually holds when something bypasses the route.
    check('users_username_format', sql`${t.username} ~ '^[a-z0-9_]{3,30}$'`),
    check('users_display_name_length', sql`length(${t.displayName}) between 1 and 60`),
    check('users_age_range', sql`${t.age} between 3 and 120`),
    check('users_languages_differ', sql`${t.nativeLanguage} <> ${t.targetLanguage}`),
  ],
);

export const vocabTerms = pgTable(
  'vocab_terms',
  {
    // Server-issued from phase 10, as users.id has been since 0001: with the
    // dictionary now written at request time, a client-generated id would mean
    // randomness in a layer ADR 0002 R1 would have to police.
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    languageCode: varchar('language_code', { length: 10 }).notNull(),
    lemma: text('lemma').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique('vocab_terms_language_lemma_key').on(t.languageCode, t.lemma)],
);

export const termVariants = pgTable(
  'term_variants',
  {
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    termId: text('term_id')
      .notNull()
      .references(() => vocabTerms.id, { onDelete: 'cascade' }),
    // Copied from the term so the unique index below can exist: the scope that
    // matters is one form in one language, but language lives on vocab_terms
    // and an index reads one table. A term's language never changes, so the
    // copy cannot go stale — and it earns its keep in the read, which no
    // longer joins vocab_terms at all.
    languageCode: varchar('language_code', { length: 10 }).notNull(),
    // Stored as it was written; matching is always lower(form). One rule for a
    // recorded `How do you do?` and for a learner who typed `BOOK`.
    form: text('form').notNull(),
    kind: text('kind').notNull(),
    // Which reading of this form this term is, as the model ranked them. It
    // sits on the variant rather than the term because it is a property of the
    // pairing: `saw` ranks `see` first, while `saws` returns `saw` alone at 0.
    entryRank: integer('entry_rank').notNull(),
  },
  (t) => [
    // Per term, so one form may belong to several terms — `saw` is a variant of
    // `see` *and* of `saw`, which is what every lexical source does.
    unique('term_variants_term_form_key').on(t.termId, t.form),
    check('term_variants_entry_rank_nonneg', sql`${t.entryRank} >= 0`),
    // Two jobs in one index. Its (language_code, lower(form)) prefix is exactly
    // the read's predicate, so there is no separate lookup index; its third
    // column enforces that no two terms claim the same reading of one form.
    // That cannot currently happen — a written form thereafter hits, and ranks
    // within one write are distinct by construction — which is the point: a
    // safety net for a write bug, exactly like UNIQUE(term_id, rank).
    uniqueIndex('term_variants_form_entry_rank_key').on(
      t.languageCode,
      sql`lower(${t.form})`,
      t.entryRank,
    ),
  ],
);

export const vocabTermSenses = pgTable(
  'vocab_term_senses',
  {
    id: text('id')
      .primaryKey()
      .default(sql`gen_random_uuid()::text`),
    termId: text('term_id')
      .notNull()
      .references(() => vocabTerms.id, { onDelete: 'cascade' }),
    // Model-supplied, and there for readability alone: senses are never merged
    // within a term, so it has no functional role. Three output tokens buys
    // financial_institution against river_bank when reading rows in psql.
    senseCode: text('sense_code').notNull(),
    // Part of speech describes a meaning, not a word: `book` is a noun (ספר)
    // and a verb (להזמין). It moved here from vocab_terms in phase 10.
    partOfSpeech: varchar('part_of_speech', { length: 50 }),
    // "Most common first", within a term. Contiguous 0..n, which is what lets
    // the read sort on the raw rank rather than a computed position.
    rank: integer('rank').notNull(),
    // The example in the term's own language. Its other half lives on the
    // translation, because that half is in the learner's language.
    exampleSource: text('example_source'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('vocab_term_senses_term_rank_key').on(t.termId, t.rank),
    check('vocab_term_senses_rank_nonneg', sql`${t.rank} >= 0`),
  ],
);

export const termSenseTranslations = pgTable(
  'term_sense_translations',
  {
    senseId: text('sense_id')
      .notNull()
      .references(() => vocabTermSenses.id, { onDelete: 'cascade' }),
    userLanguageCode: varchar('user_language_code', { length: 10 }).notNull(),
    translation: text('translation').notNull(),
    definitionNotes: text('definition_notes'),
    exampleTarget: text('example_target'),
  },
  (t) => [primaryKey({ columns: [t.senseId, t.userLanguageCode] })],
);

export const questions = pgTable(
  'questions',
  {
    id: text('id').primaryKey(),
    // Nullable: NULL means shared. Phase 4 writes only shared rows; a later
    // phase writes per-learner ones without a migration.
    userId: text('user_id').references(() => users.id),
    senseId: text('sense_id')
      .notNull()
      .references(() => vocabTermSenses.id),
    promptVariantId: text('prompt_variant_id')
      .notNull()
      .references(() => termVariants.id),
    targetLanguage: varchar('target_language', { length: 10 }).notNull(),
    userLanguageCode: varchar('user_language_code', { length: 10 }).notNull(),
    type: varchar('type', { length: 50 }).notNull(),
    options: jsonb('options').$type<QuestionOption[]>().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [check('questions_options_valid', sql`question_options_valid(${t.options})`)],
);

export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  // NULL = in progress. There is no separate `complete` column.
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

export const sessionQuestions = pgTable(
  'session_questions',
  {
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id, { onDelete: 'cascade' }),
    position: integer('position').notNull(),
    questionId: text('question_id')
      .notNull()
      .references(() => questions.id),
    // The per-session shuffle: option_order[i] is the canonical position of the
    // option shown at display index i.
    optionOrder: integer('option_order').array().notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.sessionId, t.position] }),
    // Exists purely as the composite FK target for `answers`.
    unique('session_questions_position_question_key').on(t.sessionId, t.position, t.questionId),
  ],
);

export const answers = pgTable(
  'answers',
  {
    sessionId: uuid('session_id').notNull(),
    position: integer('position').notNull(),
    questionId: text('question_id').notNull(),
    selectedOptionPosition: integer('selected_option_position').notNull(),
    answeredAt: timestamp('answered_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.sessionId, t.position] }),
    // Makes it impossible to record an answer to a question that was not in
    // this session at this position.
    foreignKey({
      columns: [t.sessionId, t.position, t.questionId],
      foreignColumns: [
        sessionQuestions.sessionId,
        sessionQuestions.position,
        sessionQuestions.questionId,
      ],
    }).onDelete('cascade'),
    check('answers_selected_option_position_nonneg', sql`${t.selectedOptionPosition} >= 0`),
  ],
);
