#!/usr/bin/env bash
#
# Prepares a git worktree for running this project.
#
# `git worktree add` brings tracked files and nothing else, so a fresh worktree
# is missing exactly what .gitignore covers: apps/mobile/.env.local and
# node_modules. The app then fails at module scope with
# "EXPO_PUBLIC_API_URL is not set", which surfaces as three unrelated-looking
# router errors rather than as the missing file it actually is.
#
# Idempotent and safe to run from any checkout, worktree or not: every step is
# guarded, so a second run does nothing. Nothing here is destructive — no file
# that already exists is overwritten.

set -u

cd "$(dirname "$0")/.." || exit 1

# The main checkout, wherever this is run from. In a worktree, --git-common-dir
# points at the original repository's .git; in a normal checkout it is that .git
# itself, and this resolves to the same tree we are already in.
MAIN=$(cd "$(git rev-parse --git-common-dir)/.." && pwd -P)
HERE=$(pwd -P)

status=0

# --- 0. the lane -------------------------------------------------------------
# A slot, and from it every port and database name this checkout will use. The
# main checkout is lane 0 and needs no .lane file; a worktree is allocated the
# lowest free slot, once, and keeps it.
if [ "$HERE" != "$MAIN" ] && [ ! -f .lane ]; then
  slot=$(bash scripts/lane-env.sh --allocate) || exit 1
  echo "  created    .lane — this checkout is lane slot $slot"
fi

eval "$(bash scripts/lane-env.sh --export)" || exit 1
echo "  ok         lane $LANE (slot $LANE_SLOT) on branch $LANE_BRANCH"
echo "             server :$PORT   metro :$METRO_PORT   database $(basename "$DATABASE_URL")"

# --- 1. the mobile env file --------------------------------------------------
# EXPO_PUBLIC_API_URL is read at module scope in apps/mobile/src/app/_layout.tsx
# (Metro inlines EXPO_PUBLIC_* at build time, which is why it is read there and
# not through an indirection). Missing file, no app.
#
# GENERATED, not copied. A copied file carries the main checkout's port, so a
# lane's app would call lane 0's server — silently, because the app works
# perfectly against the wrong server. The host comes from the main checkout's
# file, so a LAN IP set once serves every lane; the port is always this lane's.
desired="EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL"
if [ -f apps/mobile/.env.local ] && grep -qxF "$desired" apps/mobile/.env.local; then
  echo "  ok         apps/mobile/.env.local points at this lane ($EXPO_PUBLIC_API_URL)"
else
  if [ -f apps/mobile/.env.local ]; then
    echo "  rewriting  apps/mobile/.env.local — it did not point at this lane's server"
  fi
  {
    echo "# Generated by scripts/setup-worktree.sh for lane $LANE (slot $LANE_SLOT)."
    echo "# The port is this lane's; the host comes from the main checkout, or from"
    echo "# LANE_API_HOST. Re-run the script after changing either."
    echo "$desired"
  } > apps/mobile/.env.local
  echo "  created    apps/mobile/.env.local -> $EXPO_PUBLIC_API_URL"
fi

# --- 1b. the provider key ----------------------------------------------------
# Not copied from the main checkout the way .env.local is: this one is a secret
# and lives in the shell, not in a file the script can find. Reported rather
# than failed, because the tests do not need it — only `npm run server` does.
if [ -z "${GEMINI_API_KEY:-}" ]; then
  echo "  note       GEMINI_API_KEY is not set — 'npm run server' will refuse to start."
  echo "             For local work, point GEMINI_BASE_URL at MockServer and use any dummy key:"
  echo "               export GEMINI_BASE_URL=http://localhost:1080/dev GEMINI_API_KEY=dev GEMINI_MODEL=dev"
else
  echo "  ok         GEMINI_API_KEY set"
fi

# --- 2. dependencies ---------------------------------------------------------
# A worktree gets its own node_modules; there is no sharing with the main
# checkout. Roughly 700MB per worktree.
if [ -d node_modules ]; then
  echo "  ok         node_modules present"
else
  echo "  running    npm install (a worktree does not share the main checkout's)"
  npm install || status=1
fi

# --- 3. the database ---------------------------------------------------------
# One shared Postgres, one database per lane on it. `npm run db:up` is refused
# from a worktree (scripts/db-up.sh) because compose would start a second
# container; the running one is what every lane uses.
if ! command -v docker > /dev/null 2>&1; then
  echo "  note       docker not on PATH; skipping the database"
elif ! docker ps --format '{{.Image}}' 2>/dev/null | grep -q '^postgres:'; then
  echo "  note       no Postgres running. Start it from the MAIN checkout:"
  echo "               (cd $MAIN && npm run db:up)"
  echo "             then re-run this script to create $(basename "$DATABASE_URL")."
elif [ -d node_modules ]; then
  # Fresh migrate and seed, not a clone of lane 0: a lane starts from the
  # recorded seed with an empty dictionary. `npm run dict:restore` fills it from
  # data/backfill/en-he/dictionary.jsonl when a lane wants words to play with.
  echo "  running    db:migrate for $(basename "$DATABASE_URL")"
  npm run db:migrate > /dev/null || status=1
  echo "  ok         $(basename "$DATABASE_URL") migrated and seeded"
  echo "             dictionary is empty — 'npm run dict:restore' fills it"
else
  echo "  note       skipping the database: node_modules is missing above"
  status=1
fi

echo
if [ "$status" -ne 0 ]; then
  echo "Worktree setup FAILED — see the messages above." >&2
else
  echo "Worktree ready. See the Worktrees section of CLAUDE.md for what this covers."
fi

exit "$status"
